import fs from "node:fs";
import path from "node:path";
import {
  inferReleaseTypeFromParsedCommit,
  type ParsedCommit,
} from "../../infra/git/commits.js";
import { resolveRepositoryWebBaseUrl } from "../../infra/git/repo-url.js";
import type { SimplePlan } from "./plan.js";

function formatDate(): string {
  return new Date().toISOString().slice(0, 10);
}

function formatCommitMessage(subject: string): {
  label: string;
  message: string;
} {
  const conventional = subject.match(/^[a-z]+(?:\(([^)]+)\))?!?:\s+(.+)$/iu);
  if (!conventional) {
    return { label: "", message: subject };
  }

  const scope = conventional[1]?.trim();
  const message = conventional[2]?.trim() ?? subject;
  const label = scope ? `**${scope}:** ` : "";
  return { label, message };
}

function formatCommitReferences(
  commit: ParsedCommit,
  repoBaseUrl: string | null,
): string {
  const references = commit.references ?? [];
  if (references.length === 0) {
    return "";
  }

  return references
    .map((reference) => {
      const issue = reference.issue;
      if (!issue) {
        return "";
      }
      const action = (reference.action?.trim() || "refs").toLowerCase();
      if (!repoBaseUrl) {
        return `${action} #${issue}`;
      }
      return `${action} [#${issue}](${repoBaseUrl}/issues/${issue})`;
    })
    .filter((entry) => entry.length > 0)
    .join(", ");
}

function groupCommitLines(
  commits: ParsedCommit[],
  repoUrl: string | null,
): {
  breaking: string[];
  features: string[];
  fixes: string[];
} {
  const breaking: string[] = [];
  const features: string[] = [];
  const fixes: string[] = [];

  for (const commit of commits) {
    const type = inferReleaseTypeFromParsedCommit(commit);
    if (!type) {
      continue;
    }

    const { label, message } = formatCommitMessage(commit.subject);
    const short = commit.hash.slice(0, 7);
    const hashLabel = repoUrl
      ? `[\`${short}\`](${repoUrl}/commit/${commit.hash})`
      : `\`${short}\``;
    const references = formatCommitReferences(commit, repoUrl);
    const referencesSuffix = references ? `, ${references}` : "";
    const line = `- ${label}${message} (${hashLabel})${referencesSuffix}`;
    const commitType = (commit.type ?? "").toLowerCase();
    const isBreaking = type === "major";

    if (isBreaking) {
      breaking.push(line);
    }
    if (commitType === "feat" || (!isBreaking && type === "minor")) {
      features.push(line);
      continue;
    }
    if (
      commitType === "fix" ||
      commitType === "perf" ||
      (!isBreaking && type === "patch")
    ) {
      fixes.push(line);
    }
  }

  return { breaking, features, fixes };
}

export function renderSimpleReleaseNotes(
  input: {
    currentVersion: string;
    nextVersion: string;
    commits: ParsedCommit[];
    cwd?: string;
  },
  options: {
    includeFooter?: boolean;
  } = {},
): string {
  const repoUrl = resolveRepositoryWebBaseUrl(input.cwd ?? process.cwd());
  const header = repoUrl
    ? `## [${input.nextVersion}](${repoUrl}/compare/v${input.currentVersion}...v${input.nextVersion}) (${formatDate()})`
    : `## ${input.nextVersion} (${formatDate()})`;
  const grouped = groupCommitLines(input.commits, repoUrl);

  const sections: string[] = [];
  if (grouped.breaking.length > 0) {
    sections.push("### Breaking changes", ...grouped.breaking, "");
  }
  if (grouped.features.length > 0) {
    sections.push("### Features", ...grouped.features, "");
  }
  if (grouped.fixes.length > 0) {
    sections.push("### Bug Fixes", ...grouped.fixes, "");
  }

  const lines = [header, "", ...sections];
  if (options.includeFooter) {
    lines.push(
      "\n---\n\nThis PR was generated by [Versionary](https://github.com/jolars/versionary).",
    );
  }
  return lines.join("\n");
}

export function renderSimpleChangelog(plan: SimplePlan): string {
  if (!plan.nextVersion) {
    return "";
  }
  return renderSimpleReleaseNotes({
    currentVersion: plan.currentVersion,
    nextVersion: plan.nextVersion,
    commits: plan.commits,
    cwd: process.cwd(),
  });
}

export function renderPackageChangelogSection(input: {
  currentVersion: string;
  nextVersion: string;
  commits: ParsedCommit[];
  tagPrefix: string;
  cwd?: string;
}): string {
  const repoUrl = resolveRepositoryWebBaseUrl(input.cwd ?? process.cwd());
  const header = repoUrl
    ? `## [${input.nextVersion}](${repoUrl}/compare/${input.tagPrefix}-v${input.currentVersion}...${input.tagPrefix}-v${input.nextVersion}) (${formatDate()})`
    : `## ${input.nextVersion} (${formatDate()})`;
  const grouped = groupCommitLines(input.commits, repoUrl);
  const sections: string[] = [];
  if (grouped.breaking.length > 0) {
    sections.push("### Breaking changes", ...grouped.breaking, "");
  }
  if (grouped.features.length > 0) {
    sections.push("### Features", ...grouped.features, "");
  }
  if (grouped.fixes.length > 0) {
    sections.push("### Bug Fixes", ...grouped.fixes, "");
  }
  return [header, "", ...sections].join("\n");
}

export function prependChangelog(
  cwd: string,
  changelogFile: string,
  section: string,
): void {
  const changelogPath = path.join(cwd, changelogFile);
  const existing = fs.existsSync(changelogPath)
    ? fs.readFileSync(changelogPath, "utf8")
    : "";
  const heading = existing.startsWith("# Changelog") ? "" : "# Changelog\n\n";
  const separator = existing.length > 0 ? "\n" : "";
  const next =
    `${heading}${section}${separator}${existing.replace(/^# Changelog\s*/u, "")}`.trimEnd() +
    "\n";
  fs.writeFileSync(changelogPath, next, "utf8");
}
