import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

type Pull = {
  number: number;
  id: number;
  html_url: string;
  state: string;
  merged_at?: string | null;
};

interface MockGitHubApi {
  pulls: {
    list: ReturnType<typeof vi.fn>;
    update: ReturnType<typeof vi.fn>;
    create: ReturnType<typeof vi.fn>;
  };
  issues: {
    addLabels: ReturnType<typeof vi.fn>;
    createComment: ReturnType<typeof vi.fn>;
  };
  repos: {
    getReleaseByTag: ReturnType<typeof vi.fn>;
    createRelease: ReturnType<typeof vi.fn>;
  };
}

let mockApi: MockGitHubApi;
let octokitCtorCalls: Array<{ auth?: string }> = [];

vi.mock("@octokit/rest", () => {
  class MockOctokit {
    pulls = {
      list: (...args: unknown[]) => mockApi.pulls.list(...args),
      update: (...args: unknown[]) => mockApi.pulls.update(...args),
      create: (...args: unknown[]) => mockApi.pulls.create(...args),
    };

    issues = {
      addLabels: (...args: unknown[]) => mockApi.issues.addLabels(...args),
      createComment: (...args: unknown[]) =>
        mockApi.issues.createComment(...args),
    };

    repos = {
      getReleaseByTag: (...args: unknown[]) =>
        mockApi.repos.getReleaseByTag(...args),
      createRelease: (...args: unknown[]) =>
        mockApi.repos.createRelease(...args),
    };

    constructor(options?: { auth?: string }) {
      octokitCtorCalls.push({ auth: options?.auth });
    }
  }

  return { Octokit: MockOctokit };
});

import { createGitHubPlugin } from "../src/scm/github-plugin.js";

const reviewInput = {
  baseBranch: "main",
  headBranch: "versionary/release-v1.2.3",
  title: "chore(release): v1.2.3",
  body: "Generated by Versionary",
  labels: ["release", "automated"],
};

const releaseInput = {
  tag: "v1.2.3",
  version: "1.2.3",
  notes: "## Changes",
};

function pr(number: number): Pull {
  return {
    number,
    id: number * 10,
    html_url: `https://github.com/owner/repo/pull/${number}`,
    state: "open",
    merged_at: null,
  };
}

function createDefaultMockApi(): MockGitHubApi {
  return {
    pulls: {
      list: vi.fn(async () => ({ data: [] })),
      update: vi.fn(async () => ({ data: pr(12) })),
      create: vi.fn(async () => ({ data: pr(34) })),
    },
    issues: {
      addLabels: vi.fn(async () => ({ data: {} })),
      createComment: vi.fn(async () => ({ data: {} })),
    },
    repos: {
      getReleaseByTag: vi.fn(async () => ({
        data: { html_url: "https://github.com/owner/repo/releases/tag/v1.2.3" },
      })),
      createRelease: vi.fn(async () => ({
        data: { html_url: "https://github.com/owner/repo/releases/tag/v1.2.3" },
      })),
    },
  };
}

function clearGitHubEnv() {
  delete process.env.GITHUB_REPOSITORY;
  delete process.env.VERSIONARY_PR_TOKEN;
  delete process.env.GH_TOKEN;
  delete process.env.GITHUB_TOKEN;
}

describe("github plugin hardening matrix", () => {
  beforeEach(() => {
    mockApi = createDefaultMockApi();
    octokitCtorCalls = [];
    clearGitHubEnv();
  });

  afterEach(() => {
    clearGitHubEnv();
  });

  it("fails when GITHUB_REPOSITORY is missing", async () => {
    process.env.GITHUB_TOKEN = "token";
    const plugin = createGitHubPlugin();

    await expect(
      plugin.createOrUpdateReviewRequest?.(reviewInput, { cwd: process.cwd() }),
    ).rejects.toThrow("Missing GITHUB_REPOSITORY environment variable.");
  });

  it("fails when GITHUB_REPOSITORY is invalid", async () => {
    process.env.GITHUB_REPOSITORY = "owner-only";
    process.env.GITHUB_TOKEN = "token";
    const plugin = createGitHubPlugin();

    await expect(
      plugin.createOrUpdateReviewRequest?.(reviewInput, { cwd: process.cwd() }),
    ).rejects.toThrow('Invalid repo slug "owner-only". Expected "owner/repo".');
  });

  it("fails when all supported token env vars are missing", async () => {
    process.env.GITHUB_REPOSITORY = "owner/repo";
    const plugin = createGitHubPlugin();

    await expect(
      plugin.createReleaseMetadata?.(releaseInput, { cwd: process.cwd() }),
    ).rejects.toThrow(
      "Missing GitHub token. Set VERSIONARY_PR_TOKEN, GH_TOKEN, or GITHUB_TOKEN.",
    );
  });

  it("uses token precedence VERSIONARY_PR_TOKEN > GH_TOKEN > GITHUB_TOKEN", async () => {
    process.env.GITHUB_REPOSITORY = "owner/repo";
    process.env.VERSIONARY_PR_TOKEN = "preferred";
    process.env.GH_TOKEN = "secondary";
    process.env.GITHUB_TOKEN = "fallback";
    const plugin = createGitHubPlugin();

    await plugin.createOrUpdateReviewRequest?.(reviewInput, {
      cwd: process.cwd(),
    });

    expect(octokitCtorCalls[0]?.auth).toBe("preferred");
  });

  it("updates existing open PR instead of creating one", async () => {
    process.env.GITHUB_REPOSITORY = "owner/repo";
    process.env.GITHUB_TOKEN = "token";
    mockApi.pulls.list.mockResolvedValueOnce({ data: [pr(7)] });
    const plugin = createGitHubPlugin();

    const result = await plugin.createOrUpdateReviewRequest?.(reviewInput, {
      cwd: process.cwd(),
    });

    expect(mockApi.pulls.update).toHaveBeenCalledTimes(1);
    expect(mockApi.pulls.create).not.toHaveBeenCalled();
    expect(result).toMatchObject({ number: 12, state: "open" });
  });

  it("fails when more than one open PR matches same head/base", async () => {
    process.env.GITHUB_REPOSITORY = "owner/repo";
    process.env.GITHUB_TOKEN = "token";
    mockApi.pulls.list.mockResolvedValueOnce({ data: [pr(7), pr(8)] });
    const plugin = createGitHubPlugin();

    await expect(
      plugin.createOrUpdateReviewRequest?.(reviewInput, { cwd: process.cwd() }),
    ).rejects.toThrow(
      'Ambiguous open pull request matches for "versionary/release-v1.2.3" into "main": [owner/repo] #7, #8',
    );
  });

  it("creates PR when no existing open PR matches", async () => {
    process.env.GITHUB_REPOSITORY = "owner/repo";
    process.env.GITHUB_TOKEN = "token";
    const plugin = createGitHubPlugin();

    const result = await plugin.createOrUpdateReviewRequest?.(reviewInput, {
      cwd: process.cwd(),
    });

    expect(mockApi.pulls.create).toHaveBeenCalledTimes(1);
    expect(result).toMatchObject({ number: 34, state: "open" });
  });

  it("uses head owner override when provided as owner:branch", async () => {
    process.env.GITHUB_REPOSITORY = "owner/repo";
    process.env.GITHUB_TOKEN = "token";
    const plugin = createGitHubPlugin();

    await plugin.createOrUpdateReviewRequest?.(
      {
        ...reviewInput,
        headBranch: "contributor:versionary/release-v1.2.3",
      },
      { cwd: process.cwd() },
    );

    expect(mockApi.pulls.list).toHaveBeenCalledWith(
      expect.objectContaining({
        head: "contributor:versionary/release-v1.2.3",
      }),
    );
  });

  it("fails for invalid owner:branch head format", async () => {
    process.env.GITHUB_REPOSITORY = "owner/repo";
    process.env.GITHUB_TOKEN = "token";
    const plugin = createGitHubPlugin();

    await expect(
      plugin.createOrUpdateReviewRequest?.(
        {
          ...reviewInput,
          headBranch: "owneronly:",
        },
        { cwd: process.cwd() },
      ),
    ).rejects.toThrow(
      'Invalid head branch "owneronly:". Expected "branch" or "owner:branch".',
    );
  });

  it.each([
    { labelErrorStatus: 404, shouldFail: false },
    { labelErrorStatus: 422, shouldFail: false },
    { labelErrorStatus: 403, shouldFail: true },
  ])("hardens label outcomes for status $labelErrorStatus", async ({
    labelErrorStatus,
    shouldFail,
  }) => {
    process.env.GITHUB_REPOSITORY = "owner/repo";
    process.env.GITHUB_TOKEN = "token";
    const plugin = createGitHubPlugin();

    mockApi.issues.addLabels.mockRejectedValueOnce({
      status: labelErrorStatus,
      message: "label error",
    });

    const action = plugin.createOrUpdateReviewRequest?.(reviewInput, {
      cwd: process.cwd(),
    });

    if (shouldFail) {
      await expect(action).rejects.toThrow(
        "Failed applying labels to pull request #34: [owner/repo base=main head=versionary/release-v1.2.3]",
      );
    } else {
      await expect(action).resolves.toMatchObject({
        number: 34,
        state: "open",
      });
    }
  });

  it("returns merged state when GitHub response indicates merged pull request", async () => {
    process.env.GITHUB_REPOSITORY = "owner/repo";
    process.env.GITHUB_TOKEN = "token";
    mockApi.pulls.create.mockResolvedValueOnce({
      data: {
        ...pr(34),
        state: "closed",
        merged_at: "2024-01-01T00:00:00Z",
      },
    });
    const plugin = createGitHubPlugin();

    const result = await plugin.createOrUpdateReviewRequest?.(reviewInput, {
      cwd: process.cwd(),
    });

    expect(result).toMatchObject({ number: 34, state: "merged" });
  });

  it("fails when GitHub returns unexpected pull request state", async () => {
    process.env.GITHUB_REPOSITORY = "owner/repo";
    process.env.GITHUB_TOKEN = "token";
    mockApi.pulls.create.mockResolvedValueOnce({
      data: {
        ...pr(34),
        state: "draft",
        merged_at: null,
      },
    });
    const plugin = createGitHubPlugin();

    await expect(
      plugin.createOrUpdateReviewRequest?.(reviewInput, { cwd: process.cwd() }),
    ).rejects.toThrow(
      'Unexpected pull request state "draft" for pull request #34 in owner/repo.',
    );
  });

  it("returns exists when release metadata already exists by tag", async () => {
    process.env.GITHUB_REPOSITORY = "owner/repo";
    process.env.GITHUB_TOKEN = "token";
    const plugin = createGitHubPlugin();

    const result = await plugin.createReleaseMetadata?.(releaseInput, {
      cwd: process.cwd(),
    });

    expect(result).toEqual({
      status: "exists",
      url: "https://github.com/owner/repo/releases/tag/v1.2.3",
    });
    expect(mockApi.repos.createRelease).not.toHaveBeenCalled();
  });

  it("creates release metadata when lookup returns 404", async () => {
    process.env.GITHUB_REPOSITORY = "owner/repo";
    process.env.GITHUB_TOKEN = "token";
    mockApi.repos.getReleaseByTag.mockRejectedValueOnce({
      status: 404,
      message: "not found",
    });
    const plugin = createGitHubPlugin();

    const result = await plugin.createReleaseMetadata?.(releaseInput, {
      cwd: process.cwd(),
    });

    expect(mockApi.repos.createRelease).toHaveBeenCalledTimes(1);
    expect(mockApi.repos.createRelease).toHaveBeenCalledWith(
      expect.objectContaining({
        draft: false,
      }),
    );
    expect(result).toEqual({
      status: "created",
      url: "https://github.com/owner/repo/releases/tag/v1.2.3",
    });
  });

  it("creates draft release metadata when requested", async () => {
    process.env.GITHUB_REPOSITORY = "owner/repo";
    process.env.GITHUB_TOKEN = "token";
    mockApi.repos.getReleaseByTag.mockRejectedValueOnce({
      status: 404,
      message: "not found",
    });
    const plugin = createGitHubPlugin();

    const result = await plugin.createReleaseMetadata?.(
      {
        ...releaseInput,
        draft: true,
      },
      {
        cwd: process.cwd(),
      },
    );

    expect(mockApi.repos.createRelease).toHaveBeenCalledTimes(1);
    expect(mockApi.repos.createRelease).toHaveBeenCalledWith(
      expect.objectContaining({
        draft: true,
      }),
    );
    expect(result).toEqual({
      status: "created",
      url: "https://github.com/owner/repo/releases/tag/v1.2.3",
    });
  });

  it.each([
    403, 422,
  ])("fails release lookup for non-404 status %s", async (statusCode) => {
    process.env.GITHUB_REPOSITORY = "owner/repo";
    process.env.GITHUB_TOKEN = "token";
    mockApi.repos.getReleaseByTag.mockRejectedValueOnce({
      status: statusCode,
      message: "lookup denied",
    });
    const plugin = createGitHubPlugin();

    await expect(
      plugin.createReleaseMetadata?.(releaseInput, { cwd: process.cwd() }),
    ).rejects.toThrow(
      'Failed checking existing GitHub release for tag "v1.2.3":',
    );
  });

  it("posts release reference comments for issues and pull requests", async () => {
    process.env.GITHUB_REPOSITORY = "owner/repo";
    process.env.GITHUB_TOKEN = "token";
    const plugin = createGitHubPlugin();

    const result = await plugin.createReleaseReferenceComments?.(
      {
        version: "2.23.0",
        releaseUrl: "https://github.com/owner/repo/releases/tag/v2.23.0",
        references: [171, 2000000001],
      },
      { cwd: process.cwd() },
    );

    expect(result).toEqual({ commented: [171, 2000000001] });
    expect(mockApi.issues.createComment).toHaveBeenCalledWith(
      expect.objectContaining({
        issue_number: 171,
        body: "This issue has been resolved in [version 2.23.0](https://github.com/owner/repo/releases/tag/v2.23.0).",
      }),
    );
    expect(mockApi.issues.createComment).toHaveBeenCalledWith(
      expect.objectContaining({
        issue_number: 2000000001,
        body: "This pull request is included in [version 2.23.0](https://github.com/owner/repo/releases/tag/v2.23.0).",
      }),
    );
  });

  it("ignores missing references but fails on other createComment errors", async () => {
    process.env.GITHUB_REPOSITORY = "owner/repo";
    process.env.GITHUB_TOKEN = "token";
    const plugin = createGitHubPlugin();

    mockApi.issues.createComment
      .mockRejectedValueOnce({ status: 404, message: "not found" })
      .mockRejectedValueOnce({ status: 403, message: "forbidden" });

    await expect(
      plugin.createReleaseReferenceComments?.(
        {
          version: "2.23.0",
          releaseUrl: "https://github.com/owner/repo/releases/tag/v2.23.0",
          references: [171, 172],
        },
        { cwd: process.cwd() },
      ),
    ).rejects.toThrow(
      "Failed creating release reference comment on #172: [owner/repo]",
    );
  });
});
