import { describe, expect, it } from "vitest";
import {
  isReleaseCommitMessage,
  renderSimpleReviewRequestBody,
  splitSafeDirtyFiles,
} from "../src/app/release/pr.js";
import { parseConventionalCommitMessage } from "../src/infra/git/commits.js";

describe("release commit detection", () => {
  it("matches release commit pattern", () => {
    expect(isReleaseCommitMessage("chore(release): v1.2.3")).toBe(true);
    expect(isReleaseCommitMessage("chore(release): v1.2.3 (#12)")).toBe(true);
    expect(
      isReleaseCommitMessage(
        "chore(release): v1.2.3, parser-v0.4.0, code-v2.0.0 (#99)",
      ),
    ).toBe(true);
  });

  it("rejects non-release messages", () => {
    expect(isReleaseCommitMessage("feat: add feature")).toBe(false);
    expect(isReleaseCommitMessage("chore(release): prepare")).toBe(false);
  });
});

describe("safe dirty file splitting", () => {
  it("ignores lockfiles but blocks source edits", () => {
    const result = splitSafeDirtyFiles([
      "pnpm-lock.yaml",
      "src/cli/index.ts",
      "package-lock.json",
    ]);
    expect(result.ignored).toEqual(["pnpm-lock.yaml", "package-lock.json"]);
    expect(result.blocking).toEqual(["src/cli/index.ts"]);
  });

  it("blocks unknown tracked files", () => {
    const result = splitSafeDirtyFiles([
      "README.md",
      ".github/workflows/ci.yml",
    ]);
    expect(result.ignored).toEqual([]);
    expect(result.blocking).toEqual(["README.md", ".github/workflows/ci.yml"]);
  });
});

describe("review request body rendering", () => {
  it("groups releasable commits and omits ci/chore", () => {
    const prevServer = process.env.GITHUB_SERVER_URL;
    const prevRepo = process.env.GITHUB_REPOSITORY;
    let body = "";
    try {
      process.env.GITHUB_SERVER_URL = "https://github.com";
      process.env.GITHUB_REPOSITORY = "jolars/versionary";
      body = renderSimpleReviewRequestBody("1.2.3", "1.2.2", [
        {
          ...parseConventionalCommitMessage("ci: tweak workflow"),
          hash: "aaaaaaa",
        },
        {
          ...parseConventionalCommitMessage("chore: bump deps"),
          hash: "bbbbbbb",
        },
        {
          ...parseConventionalCommitMessage(
            "feat(editors): add awesome feature",
            "Closes #9",
          ),
          hash: "ccccccc1",
        },
        {
          ...parseConventionalCommitMessage("fix(lsp): patch bug"),
          hash: "ddddddd2",
        },
        {
          ...parseConventionalCommitMessage("feat!: breaking API change"),
          hash: "eeeeeee3",
        },
      ]);
    } finally {
      process.env.GITHUB_SERVER_URL = prevServer;
      process.env.GITHUB_REPOSITORY = prevRepo;
    }

    expect(body).toContain(
      "## [1.2.3](https://github.com/jolars/versionary/compare/v1.2.2...v1.2.3)",
    );
    expect(body).toContain("### Breaking changes");
    expect(body).toContain("### Features");
    expect(body).toContain("### Bug Fixes");
    expect(body).toContain(
      "- breaking API change ([`eeeeeee`](https://github.com/jolars/versionary/commit/eeeeeee3))",
    );
    expect(body).toContain(
      "- **editors:** add awesome feature ([`ccccccc`](https://github.com/jolars/versionary/commit/ccccccc1)), closes [#9](https://github.com/jolars/versionary/issues/9)",
    );
    expect(body).toContain(
      "- breaking API change ([`eeeeeee`](https://github.com/jolars/versionary/commit/eeeeeee3))",
    );
    expect(body).toContain(
      "- **lsp:** patch bug ([`ddddddd`](https://github.com/jolars/versionary/commit/ddddddd2))",
    );
    expect(body).not.toContain("ci: tweak workflow");
    expect(body).not.toContain("chore: bump deps");
    expect(body).toContain("This PR was generated by");
    expect(body).not.toContain("Release overview");
  });

  it("renders monorepo package sections", () => {
    const prevServer = process.env.GITHUB_SERVER_URL;
    const prevRepo = process.env.GITHUB_REPOSITORY;
    let body = "";
    try {
      process.env.GITHUB_SERVER_URL = "https://github.com";
      process.env.GITHUB_REPOSITORY = "jolars/versionary";
      body = renderSimpleReviewRequestBody("1.2.3", "1.2.2", [], {
        mode: "simple",
        releaseType: "minor",
        currentVersion: "1.2.2",
        nextVersion: "1.2.3",
        versionFile: "version.txt",
        changelogFile: "CHANGELOG.md",
        releaseBranchPrefix: "versionary/release",
        baselineSha: null,
        commits: [],
        packages: [
          {
            path: "packages/a",
            releaseType: "minor",
            currentVersion: "1.2.2",
            nextVersion: "1.3.0",
            commits: [
              {
                ...parseConventionalCommitMessage("feat: add A"),
                hash: "aaaaaaa1",
              },
            ],
          },
          {
            path: "packages/b",
            releaseType: "patch",
            currentVersion: "1.2.2",
            nextVersion: "1.2.3",
            commits: [
              {
                ...parseConventionalCommitMessage("fix: patch B"),
                hash: "bbbbbbb2",
              },
            ],
          },
        ],
      });
    } finally {
      process.env.GITHUB_SERVER_URL = prevServer;
      process.env.GITHUB_REPOSITORY = prevRepo;
    }

    expect(body).toContain(
      "## [packages/a: 1.3.0](https://github.com/jolars/versionary/compare/v1.2.2...v1.3.0)",
    );
    expect(body).toContain(
      "## [packages/b: 1.2.3](https://github.com/jolars/versionary/compare/v1.2.2...v1.2.3)",
    );
    expect(body).not.toContain("<details>");
    expect(body).not.toContain("<summary>");
    expect(body).toContain("### Features");
    expect(body).toContain("### Bug Fixes");
    expect(body).toContain("This PR was generated by");
  });

  it("uses repository directory name for root package section labels", () => {
    const prevServer = process.env.GITHUB_SERVER_URL;
    const prevRepo = process.env.GITHUB_REPOSITORY;
    let body = "";
    try {
      process.env.GITHUB_SERVER_URL = "https://github.com";
      process.env.GITHUB_REPOSITORY = "jolars/panache";
      body = renderSimpleReviewRequestBody(
        "2.35.0",
        "2.34.0",
        [],
        {
          mode: "simple",
          releaseType: "minor",
          currentVersion: "2.34.0",
          nextVersion: "2.35.0",
          versionFile: "version.txt",
          changelogFile: "CHANGELOG.md",
          releaseBranchPrefix: "versionary/release",
          baselineSha: null,
          commits: [],
          packages: [
            {
              path: ".",
              releaseType: "minor",
              currentVersion: "2.34.0",
              nextVersion: "2.35.0",
              commits: [
                {
                  ...parseConventionalCommitMessage(
                    "feat: improve root package",
                  ),
                  hash: "aaaaaaa1",
                },
              ],
            },
            {
              path: "crates/panache-parser",
              releaseType: "minor",
              currentVersion: "0.3.0",
              nextVersion: "0.4.0",
              commits: [
                {
                  ...parseConventionalCommitMessage("feat: improve parser"),
                  hash: "bbbbbbb2",
                },
              ],
            },
          ],
        },
        "/tmp/panache",
      );
    } finally {
      process.env.GITHUB_SERVER_URL = prevServer;
      process.env.GITHUB_REPOSITORY = prevRepo;
    }

    expect(body).toContain(
      "## [panache: 2.35.0](https://github.com/jolars/panache/compare/v2.34.0...v2.35.0)",
    );
    expect(body).not.toContain("## [.: 2.35.0]");
    expect(body).toContain(
      "## [crates/panache-parser: 0.4.0](https://github.com/jolars/panache/compare/v0.3.0...v0.4.0)",
    );
  });

  it("falls back to single release body for single-package plans", () => {
    const prevServer = process.env.GITHUB_SERVER_URL;
    const prevRepo = process.env.GITHUB_REPOSITORY;
    let body = "";
    try {
      process.env.GITHUB_SERVER_URL = "https://github.com";
      process.env.GITHUB_REPOSITORY = "jolars/versionary";
      body = renderSimpleReviewRequestBody(
        "0.3.0",
        "0.2.0",
        [
          {
            ...parseConventionalCommitMessage("feat: improve UX"),
            hash: "aaaaaaa1",
          },
        ],
        {
          mode: "simple",
          releaseType: "minor",
          currentVersion: "0.2.0",
          nextVersion: "0.3.0",
          versionFile: "version.txt",
          changelogFile: "CHANGELOG.md",
          releaseBranchPrefix: "versionary/release",
          baselineSha: null,
          commits: [
            {
              ...parseConventionalCommitMessage("feat: improve UX"),
              hash: "aaaaaaa1",
            },
          ],
          packages: [
            {
              path: ".",
              releaseType: "minor",
              currentVersion: "0.2.0",
              nextVersion: "0.3.0",
              commits: [
                {
                  ...parseConventionalCommitMessage("feat: improve UX"),
                  hash: "aaaaaaa1",
                },
              ],
            },
          ],
        },
      );
    } finally {
      process.env.GITHUB_SERVER_URL = prevServer;
      process.env.GITHUB_REPOSITORY = prevRepo;
    }

    expect(body).toContain(
      "## [0.3.0](https://github.com/jolars/versionary/compare/v0.2.0...v0.3.0)",
    );
    expect(body).not.toContain("## [.: 0.3.0]");
    expect(body).not.toContain("<details>");
    expect(body).toContain("This PR was generated by");
  });
});
