import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { loadConfig } from "../config/load-config.js";
import { findPluginsByCapability } from "../plugins/capabilities.js";
import { loadRuntimePlugins } from "../plugins/runtime.js";
import { createSimplePlan } from "./plan.js";
import { prependChangelog, renderSimpleChangelog } from "./changelog.js";
import { getBaselineStatePath, writeBaselineSha } from "./state.js";

function ensureCleanWorktree(cwd: string): void {
  const status = execFileSync("git", ["status", "--porcelain"], {
    cwd,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  }).trim();

  if (status.length > 0) {
    throw new Error("Working tree is not clean. Commit or stash changes before `versionary pr`.");
  }
}

export function prepareSimpleReleasePr(cwd = process.cwd()): {
  branch: string;
  title: string;
  version: string;
} {
  const plan = createSimplePlan(cwd);
  if (!plan.nextVersion) {
    throw new Error("No releasable commits found. Nothing to open a release PR for.");
  }

  ensureCleanWorktree(cwd);

  const versionPath = path.join(cwd, plan.versionFile);
  fs.writeFileSync(versionPath, `${plan.nextVersion}\n`, "utf8");
  const section = renderSimpleChangelog(plan);
  prependChangelog(cwd, plan.changelogFile, section);

  const branch = plan.releaseBranchPrefix;
  const title = `chore(release): v${plan.nextVersion}`;

  execFileSync("git", ["checkout", "-B", branch], { cwd, stdio: ["ignore", "pipe", "ignore"] });
  execFileSync("git", ["add", plan.versionFile, plan.changelogFile], {
    cwd,
    stdio: ["ignore", "pipe", "ignore"],
  });
  execFileSync("git", ["commit", "-m", title], { cwd, stdio: ["ignore", "pipe", "ignore"] });
  writeBaselineSha(cwd);
  execFileSync("git", ["add", getBaselineStatePath(cwd)], {
    cwd,
    stdio: ["ignore", "pipe", "ignore"],
  });
  execFileSync("git", ["commit", "--amend", "--no-edit"], { cwd, stdio: ["ignore", "pipe", "ignore"] });

  return {
    branch,
    title,
    version: plan.nextVersion,
  };
}

export async function openOrUpdateSimpleReviewRequest(
  cwd: string,
  branch: string,
  title: string,
  version: string,
): Promise<string> {
  const loaded = loadConfig(cwd);
  const releaseFlow = loaded.config.releaseFlow?.mode ?? "direct";
  if (releaseFlow !== "review") {
    return "Release flow mode is direct; skipping review request creation.";
  }

  const plugins = loadRuntimePlugins();
  const scmPlugins = findPluginsByCapability(plugins, "scm.reviewRequest");
  if (scmPlugins.length === 0) {
    throw new Error("releaseFlow.mode is review but no scm.reviewRequest plugin is available.");
  }

  const plugin = scmPlugins[0];
  if (!plugin?.createOrUpdateReviewRequest) {
    throw new Error(`Plugin "${plugin?.name ?? "unknown"}" does not implement createOrUpdateReviewRequest.`);
  }

  const result = await plugin.createOrUpdateReviewRequest(
    {
      baseBranch: process.env.VERSIONARY_BASE_BRANCH ?? "main",
      headBranch: branch,
      title,
      body: `Automated release PR for v${version} generated by Versionary.`,
      labels: ["release"],
    },
    {
      cwd,
      logger: console,
    },
  );

  return result.url;
}

export function pushReleaseBranch(cwd: string, branch: string): void {
  execFileSync("git", ["push", "--force-with-lease", "origin", branch], {
    cwd,
    stdio: ["ignore", "pipe", "ignore"],
  });
}

export function isReleaseCommitMessage(subject: string): boolean {
  return /^chore\(release\):\sv\d+\.\d+\.\d+/u.test(subject);
}
