import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { loadConfig } from "../config/load-config.js";
import { findPluginsByCapability } from "../plugins/capabilities.js";
import { loadRuntimePlugins } from "../plugins/runtime.js";
import { createSimplePlan } from "./plan.js";
import type { CommitInfo } from "./git.js";
import { inferReleaseTypeFromSubject } from "./git.js";
import { prependChangelog, renderSimpleChangelog } from "./changelog.js";
import { getBaselineStatePath, writeBaselineSha } from "./state.js";

const SAFE_DIRTY_FILES = new Set([
  "pnpm-lock.yaml",
  "package-lock.json",
  "yarn.lock",
  "bun.lockb",
  "npm-shrinkwrap.json",
]);

function listTrackedDirtyFiles(cwd: string): string[] {
  const status = execFileSync("git", ["status", "--porcelain", "--untracked-files=no"], {
    cwd,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  });

  return status
    .split("\n")
    .filter((line) => line.length > 0)
    .map((line) => line.slice(3))
    .map((pathPart) => {
      const renameParts = pathPart.split(" -> ");
      return renameParts.at(-1) ?? pathPart;
    })
    .map((filePath) => filePath.trim())
    .filter((filePath) => filePath.length > 0);
}

export function splitSafeDirtyFiles(files: string[]): { ignored: string[]; blocking: string[] } {
  const ignored: string[] = [];
  const blocking: string[] = [];
  for (const file of files) {
    const basename = path.basename(file);
    if (SAFE_DIRTY_FILES.has(basename)) {
      ignored.push(file);
      continue;
    }
    blocking.push(file);
  }
  return { ignored, blocking };
}

function ensureCleanWorktree(cwd: string): void {
  const dirtyFiles = listTrackedDirtyFiles(cwd);
  const { ignored, blocking } = splitSafeDirtyFiles(dirtyFiles);

  if (blocking.length > 0) {
    throw new Error(
      `Working tree has tracked modifications before versionary pr:\n${blocking.join("\n")}\nCommit/stash tracked changes first.`,
    );
  }

  if (ignored.length > 0) {
    console.warn(`Ignoring safe tracked changes before versionary pr:\n${ignored.join("\n")}`);
  }
}

export function prepareSimpleReleasePr(cwd = process.cwd()): {
  branch: string;
  title: string;
  version: string;
  commits: CommitInfo[];
} {
  const plan = createSimplePlan(cwd);
  if (!plan.nextVersion) {
    throw new Error("No releasable commits found. Nothing to open a release PR for.");
  }

  ensureCleanWorktree(cwd);

  const versionPath = path.join(cwd, plan.versionFile);
  fs.writeFileSync(versionPath, `${plan.nextVersion}\n`, "utf8");
  const section = renderSimpleChangelog(plan);
  prependChangelog(cwd, plan.changelogFile, section);

  const branch = plan.releaseBranchPrefix;
  const title = `chore(release): v${plan.nextVersion}`;

  execFileSync("git", ["checkout", "-B", branch], { cwd, stdio: ["ignore", "pipe", "ignore"] });
  execFileSync("git", ["add", plan.versionFile, plan.changelogFile], {
    cwd,
    stdio: ["ignore", "pipe", "ignore"],
  });
  execFileSync("git", ["commit", "-m", title], { cwd, stdio: ["ignore", "pipe", "ignore"] });
  writeBaselineSha(cwd);
  execFileSync("git", ["add", getBaselineStatePath(cwd)], {
    cwd,
    stdio: ["ignore", "pipe", "ignore"],
  });
  execFileSync("git", ["commit", "--amend", "--no-edit"], { cwd, stdio: ["ignore", "pipe", "ignore"] });

  return {
    branch,
    title,
    version: plan.nextVersion,
    commits: plan.commits,
  };
}

export function renderSimpleReviewRequestBody(version: string, commits: CommitInfo[]): string {
  const breaking: string[] = [];
  const features: string[] = [];
  const fixes: string[] = [];

  for (const commit of commits) {
    const subject = commit.subject;
    const hash = commit.hash.slice(0, 7);
    const type = inferReleaseTypeFromSubject(subject);
    if (!type) {
      continue;
    }

    const item = `- ${subject} (${hash})`;
    if (type === "major") {
      breaking.push(item);
      continue;
    }

    if (type === "minor") {
      features.push(item);
      continue;
    }

    fixes.push(item);
  }

  const sections: string[] = [];
  if (breaking.length > 0) {
    sections.push("### Breaking changes", ...breaking, "");
  }
  if (features.length > 0) {
    sections.push("### Features", ...features, "");
  }
  if (fixes.length > 0) {
    sections.push("### Fixes", ...fixes, "");
  }

  return [
    ":robot: I have created a release PR for this repository.",
    "",
    `## Version`,
    "",
    `This PR prepares **v${version}**.`,
    "",
    "## Release notes preview",
    "",
    ...sections,
    "This PR was generated by Versionary.",
  ].join("\n");
}

export async function openOrUpdateSimpleReviewRequest(
  cwd: string,
  branch: string,
  title: string,
  version: string,
  commits: CommitInfo[],
): Promise<string> {
  const loaded = loadConfig(cwd);
  const releaseFlow = loaded.config.releaseFlow?.mode ?? "direct";
  if (releaseFlow !== "review") {
    return "Release flow mode is direct; skipping review request creation.";
  }

  const plugins = loadRuntimePlugins();
  const scmPlugins = findPluginsByCapability(plugins, "scm.reviewRequest");
  if (scmPlugins.length === 0) {
    throw new Error("releaseFlow.mode is review but no scm.reviewRequest plugin is available.");
  }

  const plugin = scmPlugins[0];
  if (!plugin?.createOrUpdateReviewRequest) {
    throw new Error(`Plugin "${plugin?.name ?? "unknown"}" does not implement createOrUpdateReviewRequest.`);
  }

  const result = await plugin.createOrUpdateReviewRequest(
    {
      baseBranch: process.env.VERSIONARY_BASE_BRANCH ?? "main",
      headBranch: branch,
      title,
      body: renderSimpleReviewRequestBody(version, commits),
      labels: ["release"],
    },
    {
      cwd,
      logger: console,
    },
  );

  return result.url;
}

export function pushReleaseBranch(cwd: string, branch: string): void {
  execFileSync("git", ["push", "--force-with-lease", "origin", branch], {
    cwd,
    stdio: ["ignore", "pipe", "ignore"],
  });
}

export function isReleaseCommitMessage(subject: string): boolean {
  return /^chore\(release\):\sv\d+\.\d+\.\d+/u.test(subject);
}
