import fs from "node:fs";
import path from "node:path";
import {
  inferReleaseTypeFromParsedCommit,
  type ParsedCommit,
  parseConventionalCommitMessage,
} from "../git/commits.js";
import { resolveRepositoryWebBaseUrl } from "../git/repo-url.js";
import type { VersionaryChangelogFormat } from "../types/config.js";
import type { ReleasePlan, SimplePlan } from "./plan.js";

const REVIEW_REQUEST_FOOTER =
  "---\n\nThis PR was generated by [Versionary](https://github.com/jolars/versionary).";

function formatDate(): string {
  return new Date().toISOString().slice(0, 10);
}

function formatCommitMessage(subject: string): {
  label: string;
  message: string;
} {
  const conventional = subject.match(/^[a-z]+(?:\(([^)]+)\))?!?:\s+(.+)$/iu);
  if (!conventional) {
    return { label: "", message: subject };
  }

  const scope = conventional[1]?.trim();
  const message = conventional[2]?.trim() ?? subject;
  const label = scope ? `**${scope}:** ` : "";
  return { label, message };
}

function formatCommitReferences(
  commit: ParsedCommit,
  repoBaseUrl: string | null,
): string {
  const references = commit.references ?? [];
  if (references.length === 0) {
    return "";
  }

  const formatIssueList = (issues: string[]): string => {
    if (issues.length === 0) {
      return "";
    }
    if (issues.length === 1) {
      return issues[0] ?? "";
    }
    if (issues.length === 2) {
      return `${issues[0] ?? ""} and ${issues[1] ?? ""}`;
    }
    return `${issues.slice(0, -1).join(", ")}, and ${issues[issues.length - 1] ?? ""}`;
  };

  const referencesByAction = new Map<string, string[]>();
  for (const reference of references) {
    const issue = reference.issue;
    if (!issue) {
      continue;
    }
    const action = (reference.action?.trim() || "refs").toLowerCase();
    const formattedIssue = repoBaseUrl
      ? `[#${issue}](${repoBaseUrl}/issues/${issue})`
      : `#${issue}`;
    const existing = referencesByAction.get(action) ?? [];
    if (!existing.includes(formattedIssue)) {
      existing.push(formattedIssue);
      referencesByAction.set(action, existing);
    }
  }

  return [...referencesByAction.entries()]
    .map(([action, issues]) => {
      const list = formatIssueList(issues);
      if (list.length === 0) {
        return "";
      }
      return `${action} ${list}`;
    })
    .filter((entry) => entry.length > 0)
    .join(", ");
}

function groupCommitLines(
  commits: ParsedCommit[],
  repoUrl: string | null,
): {
  breaking: string[];
  features: string[];
  fixes: string[];
  reverts: string[];
} {
  const breaking: string[] = [];
  const features: string[] = [];
  const fixes: string[] = [];
  const reverts: string[] = [];

  const getRevertedSubject = (commit: ParsedCommit): string => {
    const normalizedDescription = (commit.description ?? "")
      .trim()
      .replace(/^"(.*)"$/u, "$1");
    if (normalizedDescription.length > 0) {
      return normalizedDescription;
    }

    const quoted = commit.subject.match(/^revert:\s+"(.+)"$/iu);
    if (quoted) {
      return quoted[1].trim();
    }

    const plain = commit.subject.match(/^revert:\s+(.+)$/iu);
    return plain ? plain[1].trim() : "";
  };

  const shouldIncludeRevert = (commit: ParsedCommit): boolean => {
    const revertedSubject = getRevertedSubject(commit);
    if (revertedSubject.length === 0) {
      return true;
    }
    const revertedCommit = parseConventionalCommitMessage(revertedSubject);
    return inferReleaseTypeFromParsedCommit(revertedCommit) !== null;
  };

  for (const commit of commits) {
    const type = inferReleaseTypeFromParsedCommit(commit);
    if (!type) {
      continue;
    }

    const { label, message } = formatCommitMessage(commit.subject);
    const short = commit.hash.slice(0, 7);
    const hashLabel = repoUrl
      ? `[\`${short}\`](${repoUrl}/commit/${commit.hash})`
      : `\`${short}\``;
    const references = formatCommitReferences(commit, repoUrl);
    const referencesSuffix = references ? `, ${references}` : "";
    const line = `- ${label}${message} (${hashLabel})${referencesSuffix}`;
    const commitType = (commit.type ?? "").toLowerCase();
    const isBreaking = type === "major";

    if (commit.isRevert) {
      if (!shouldIncludeRevert(commit)) {
        continue;
      }
      reverts.push(line);
      continue;
    }

    if (isBreaking) {
      breaking.push(line);
    }
    if (commitType === "feat" || (!isBreaking && type === "minor")) {
      features.push(line);
      continue;
    }
    if (
      commitType === "fix" ||
      commitType === "perf" ||
      (!isBreaking && type === "patch")
    ) {
      fixes.push(line);
    }
  }

  return { breaking, features, fixes, reverts };
}

export function renderSimpleReleaseNotes(
  input: {
    currentVersion: string;
    nextVersion: string;
    commits: ParsedCommit[];
    cwd?: string;
    dependencies?: Array<{
      name: string;
      version: string;
    }>;
  },
  options: {
    includeFooter?: boolean;
    headerLabel?: string;
  } = {},
): string {
  const repoUrl = resolveRepositoryWebBaseUrl(input.cwd ?? process.cwd());
  const headerLabel = options.headerLabel ?? input.nextVersion;
  const header = repoUrl
    ? `## [${headerLabel}](${repoUrl}/compare/v${input.currentVersion}...v${input.nextVersion}) (${formatDate()})`
    : `## ${headerLabel} (${formatDate()})`;
  const grouped = groupCommitLines(input.commits, repoUrl);

  const sections: string[] = [];
  if (grouped.breaking.length > 0) {
    sections.push("### Breaking changes", ...grouped.breaking, "");
  }
  if (grouped.features.length > 0) {
    sections.push("### Features", ...grouped.features, "");
  }
  if (grouped.fixes.length > 0) {
    sections.push("### Bug Fixes", ...grouped.fixes, "");
  }
  if (grouped.reverts.length > 0) {
    sections.push("### Reverts", ...grouped.reverts, "");
  }
  if (input.dependencies && input.dependencies.length > 0) {
    sections.push(
      "### Dependencies",
      ...input.dependencies.map(
        (dependency) =>
          `- updated ${dependency.name} to v${dependency.version}`,
      ),
      "",
    );
  }
  const body = [header, "", ...sections].join("\n").trimEnd();
  if (options.includeFooter) {
    return `${body}\n\n${renderReviewRequestFooter()}`;
  }
  return body;
}

export function renderReviewRequestFooter(): string {
  return REVIEW_REQUEST_FOOTER;
}

export function renderReleasePlanChangelog(
  plan: ReleasePlan,
  options: {
    headerLabel?: string;
    includeFooter?: boolean;
    cwd?: string;
  } = {},
): string {
  if (!plan.nextVersion) {
    return "";
  }
  const propagatedRootPackage = plan.packages?.find(
    (pkg) => pkg.path === "." && pkg.bumpReason === "dependency-propagation",
  );
  const isDirectBump = (
    pkg: NonNullable<SimplePlan["packages"]>[number],
  ): boolean =>
    pkg.bumpReason === "direct" ||
    (pkg.bumpReason === undefined &&
      Boolean(pkg.nextVersion) &&
      pkg.commits.length > 0);
  const dependencies =
    propagatedRootPackage && plan.packages
      ? plan.packages
          .filter(
            (pkg) => pkg.path !== "." && isDirectBump(pkg) && pkg.nextVersion,
          )
          .map((pkg) => ({
            name: pkg.path,
            version: pkg.nextVersion as string,
          }))
      : [];
  const dedupedCommits = [
    ...new Map(plan.commits.map((commit) => [commit.hash, commit])).values(),
  ];
  if (plan.changelogFormat === "r-news") {
    return renderRNewsReleaseNotes({
      packageName: plan.packageName,
      nextVersion: plan.nextVersion,
      commits: dedupedCommits,
      cwd: process.cwd(),
    });
  }
  return renderSimpleReleaseNotes(
    {
      currentVersion: plan.currentVersion,
      nextVersion: plan.nextVersion,
      commits: dedupedCommits,
      cwd: options.cwd ?? process.cwd(),
      dependencies,
    },
    {
      includeFooter: options.includeFooter,
      headerLabel: options.headerLabel,
    },
  );
}

/** @deprecated Use renderReleasePlanChangelog. */
export function renderSimpleChangelog(plan: SimplePlan): string {
  return renderReleasePlanChangelog(plan);
}

export function renderPackageChangelogSection(input: {
  currentVersion: string;
  nextVersion: string;
  commits: ParsedCommit[];
  tagPrefix: string;
  cwd?: string;
}): string {
  const repoUrl = resolveRepositoryWebBaseUrl(input.cwd ?? process.cwd());
  const header = repoUrl
    ? `## [${input.nextVersion}](${repoUrl}/compare/${input.tagPrefix}-v${input.currentVersion}...${input.tagPrefix}-v${input.nextVersion}) (${formatDate()})`
    : `## ${input.nextVersion} (${formatDate()})`;
  const grouped = groupCommitLines(input.commits, repoUrl);
  const sections: string[] = [];
  if (grouped.breaking.length > 0) {
    sections.push("### Breaking changes", ...grouped.breaking, "");
  }
  if (grouped.features.length > 0) {
    sections.push("### Features", ...grouped.features, "");
  }
  if (grouped.fixes.length > 0) {
    sections.push("### Bug Fixes", ...grouped.fixes, "");
  }
  if (grouped.reverts.length > 0) {
    sections.push("### Reverts", ...grouped.reverts, "");
  }
  return [header, "", ...sections].join("\n");
}

export function prependChangelog(
  cwd: string,
  changelogFile: string,
  section: string,
  format: VersionaryChangelogFormat = "markdown-changelog",
): void {
  const changelogPath = path.join(cwd, changelogFile);
  const existing = fs.existsSync(changelogPath)
    ? fs.readFileSync(changelogPath, "utf8")
    : "";
  if (format === "r-news") {
    const bodyWithoutDevHeader = existing.replace(
      /^#\s+.+\s+\(development version\)\s*(?:\r?\n)*/u,
      "",
    );
    const separator = bodyWithoutDevHeader.length > 0 ? "\n\n" : "";
    const next = `${`${section}${separator}${bodyWithoutDevHeader}`.trimEnd()}\n`;
    fs.writeFileSync(changelogPath, next, "utf8");
    return;
  }
  const heading = "# Changelog\n\n";
  const bodyWithoutHeading = existing.replace(/^# Changelog\s*/u, "");
  const separator = existing.length > 0 ? "\n" : "";
  const next = `${`${heading}${section}${separator}${bodyWithoutHeading}`.trimEnd()}\n`;
  fs.writeFileSync(changelogPath, next, "utf8");
}

export function renderRNewsReleaseNotes(input: {
  packageName: string;
  nextVersion: string;
  commits: ParsedCommit[];
  cwd?: string;
}): string {
  const repoUrl = resolveRepositoryWebBaseUrl(input.cwd ?? process.cwd());
  const grouped = groupCommitLines(input.commits, repoUrl);
  const normalizedVersion = input.nextVersion.replace(/\.\d+$/u, "");
  const sections: string[] = [];
  if (grouped.breaking.length > 0) {
    sections.push("## Breaking changes", "", ...grouped.breaking, "");
  }
  if (grouped.features.length > 0) {
    sections.push("## Features", "", ...grouped.features, "");
  }
  if (grouped.fixes.length > 0) {
    sections.push("## Bug fixes", "", ...grouped.fixes, "");
  }
  if (grouped.reverts.length > 0) {
    sections.push("## Reverts", "", ...grouped.reverts, "");
  }
  return [`# ${input.packageName} ${normalizedVersion}`, "", ...sections]
    .join("\n")
    .trimEnd();
}
