import fs from "node:fs";
import path from "node:path";
import {
  applyRevertSuppression,
  inferReleaseTypeFromParsedCommit,
  type ParsedCommit,
  parseConventionalCommitMessage,
} from "../git/commits.js";
import { resolveRepositoryWebBaseUrl } from "../git/repo-url.js";
import type { VersionaryChangelogFormat } from "../types/config.js";
import { type ReleasePlan, resolvePackageDependencies } from "./plan.js";
import { isVersionHeading } from "./semver.js";

const REVIEW_REQUEST_FOOTER =
  "---\n\nThis PR was generated by [Versionary](https://github.com/jolars/versionary).";

function formatDate(): string {
  return new Date().toISOString().slice(0, 10);
}

function formatCommitMessage(subject: string): {
  label: string;
  message: string;
} {
  const conventional = subject.match(/^[a-z]+(?:\(([^)]+)\))?!?:\s+(.+)$/iu);
  if (!conventional) {
    return { label: "", message: subject };
  }

  const scope = conventional[1]?.trim();
  const message = conventional[2]?.trim() ?? subject;
  const label = scope ? `**${scope}:** ` : "";
  return { label, message };
}

function formatCommitReferences(
  commit: ParsedCommit,
  repoBaseUrl: string | null,
): string {
  const references = commit.references ?? [];
  if (references.length === 0) {
    return "";
  }

  const formatIssueList = (issues: string[]): string => {
    if (issues.length === 0) {
      return "";
    }
    if (issues.length === 1) {
      return issues[0] ?? "";
    }
    if (issues.length === 2) {
      return `${issues[0] ?? ""} and ${issues[1] ?? ""}`;
    }
    return `${issues.slice(0, -1).join(", ")}, and ${issues[issues.length - 1] ?? ""}`;
  };

  const referencesByAction = new Map<string, string[]>();
  for (const reference of references) {
    const issue = reference.issue;
    if (!issue) {
      continue;
    }
    const action = (reference.action?.trim() || "refs").toLowerCase();
    const formattedIssue = repoBaseUrl
      ? `[#${issue}](${repoBaseUrl}/issues/${issue})`
      : `#${issue}`;
    const existing = referencesByAction.get(action) ?? [];
    if (!existing.includes(formattedIssue)) {
      existing.push(formattedIssue);
      referencesByAction.set(action, existing);
    }
  }

  return [...referencesByAction.entries()]
    .map(([action, issues]) => {
      const list = formatIssueList(issues);
      if (list.length === 0) {
        return "";
      }
      return `${action} ${list}`;
    })
    .filter((entry) => entry.length > 0)
    .join(", ");
}

function groupCommitLines(
  commits: ParsedCommit[],
  repoUrl: string | null,
): {
  breaking: string[];
  features: string[];
  fixes: string[];
  performance: string[];
  reverts: string[];
  other: string[];
} {
  const breaking: string[] = [];
  const features: string[] = [];
  const fixes: string[] = [];
  const performance: string[] = [];
  const reverts: string[] = [];
  const other: string[] = [];
  const effectiveCommits = applyRevertSuppression(commits);

  const getRevertedSubject = (commit: ParsedCommit): string => {
    const normalizedDescription = (commit.description ?? "")
      .trim()
      .replace(/^"(.*)"$/u, "$1");
    if (normalizedDescription.length > 0) {
      return normalizedDescription;
    }

    const quoted = commit.subject.match(/^revert:\s+"(.+)"$/iu);
    if (quoted) {
      return quoted[1].trim();
    }

    const plain = commit.subject.match(/^revert:\s+(.+)$/iu);
    return plain ? plain[1].trim() : "";
  };

  const shouldIncludeRevert = (commit: ParsedCommit): boolean => {
    const revertedSubject = getRevertedSubject(commit);
    if (revertedSubject.length === 0) {
      return true;
    }
    const revertedCommit = parseConventionalCommitMessage(revertedSubject);
    return inferReleaseTypeFromParsedCommit(revertedCommit) !== null;
  };

  for (const commit of effectiveCommits) {
    const type = inferReleaseTypeFromParsedCommit(commit);

    const { label, message } = formatCommitMessage(commit.subject);
    const short = commit.hash.slice(0, 7);
    const hashLabel = repoUrl
      ? `[\`${short}\`](${repoUrl}/commit/${commit.hash})`
      : `\`${short}\``;
    const references = formatCommitReferences(commit, repoUrl);
    const referencesSuffix = references ? `, ${references}` : "";
    const line = `- ${label}${message} (${hashLabel})${referencesSuffix}`;
    const commitType = (commit.type ?? "").toLowerCase();
    const isBreaking = type === "major";

    if (!type) {
      other.push(line);
      continue;
    }

    if (commit.isRevert) {
      if (!shouldIncludeRevert(commit)) {
        continue;
      }
      reverts.push(line);
      continue;
    }

    if (isBreaking) {
      breaking.push(line);
    }
    if (commitType === "feat" || (!isBreaking && type === "minor")) {
      features.push(line);
      continue;
    }
    if (commitType === "perf") {
      performance.push(line);
      continue;
    }
    if (commitType === "fix" || (!isBreaking && type === "patch")) {
      fixes.push(line);
    }
  }

  return { breaking, features, fixes, performance, reverts, other };
}

/**
 * A forced bump — a stale dependency, or a propagated requirement rewrite —
 * can carry no release-worthy commits at all. Rather than publish a bare
 * version heading, such a release falls back to listing whatever else is
 * shipping under it.
 */
function needsOtherChangesFallback(
  grouped: ReturnType<typeof groupCommitLines>,
  hasHighlights: boolean,
  dependencyCount: number,
): boolean {
  if (hasHighlights || dependencyCount > 0 || grouped.other.length === 0) {
    return false;
  }
  return (
    grouped.breaking.length === 0 &&
    grouped.features.length === 0 &&
    grouped.fixes.length === 0 &&
    grouped.performance.length === 0 &&
    grouped.reverts.length === 0
  );
}

export function renderReleaseNotesSection(
  input: {
    currentVersion: string;
    nextVersion: string;
    commits: ParsedCommit[];
    cwd?: string;
    dependencies?: Array<{
      name: string;
      version: string;
    }>;
    highlights?: string;
    tagPrefix?: string;
    headerLabel?: string;
  },
  options: {
    includeFooter?: boolean;
  } = {},
): string {
  const repoUrl = resolveRepositoryWebBaseUrl(input.cwd ?? process.cwd());
  const headerLabel = input.headerLabel ?? input.nextVersion;
  const versionPrefix = input.tagPrefix ? `${input.tagPrefix}-v` : "v";
  const header = repoUrl
    ? `## [${headerLabel}](${repoUrl}/compare/${versionPrefix}${input.currentVersion}...${versionPrefix}${input.nextVersion}) (${formatDate()})`
    : `## ${headerLabel} (${formatDate()})`;
  const grouped = groupCommitLines(input.commits, repoUrl);

  const sections: string[] = [];
  const trimmedHighlights = input.highlights?.trim() ?? "";
  if (trimmedHighlights.length > 0) {
    sections.push(trimmedHighlights, "");
  }
  if (grouped.breaking.length > 0) {
    sections.push("### Breaking changes", ...grouped.breaking, "");
  }
  if (grouped.features.length > 0) {
    sections.push("### Features", ...grouped.features, "");
  }
  if (grouped.fixes.length > 0) {
    sections.push("### Bug Fixes", ...grouped.fixes, "");
  }
  if (grouped.performance.length > 0) {
    sections.push("### Performance Improvements", ...grouped.performance, "");
  }
  if (grouped.reverts.length > 0) {
    sections.push("### Reverts", ...grouped.reverts, "");
  }
  if (input.dependencies && input.dependencies.length > 0) {
    sections.push(
      "### Dependencies",
      ...input.dependencies.map(
        (dependency) =>
          `- updated ${dependency.name} to v${dependency.version}`,
      ),
      "",
    );
  }
  if (
    needsOtherChangesFallback(
      grouped,
      trimmedHighlights.length > 0,
      input.dependencies?.length ?? 0,
    )
  ) {
    sections.push("### Other changes", ...grouped.other, "");
  }
  const body = [header, "", ...sections].join("\n").trimEnd();
  if (options.includeFooter) {
    return `${body}\n\n${renderReviewRequestFooter()}`;
  }
  return body;
}

export function renderReviewRequestFooter(): string {
  return REVIEW_REQUEST_FOOTER;
}

export function renderReleasePlanChangelog(
  plan: ReleasePlan,
  options: {
    headerLabel?: string;
    includeFooter?: boolean;
    cwd?: string;
    highlights?: string;
  } = {},
): string {
  if (!plan.nextVersion) {
    return "";
  }
  const dedupedCommits = [
    ...new Map(plan.commits.map((commit) => [commit.hash, commit])).values(),
  ];
  if (plan.changelogFormat === "r-news") {
    return renderRNewsReleaseNotes({
      packageName: plan.packageName,
      nextVersion: plan.nextVersion,
      commits: dedupedCommits,
      cwd: process.cwd(),
      highlights: options.highlights,
    });
  }
  return renderReleaseNotesSection(
    {
      currentVersion: plan.currentVersion,
      nextVersion: plan.nextVersion,
      commits: dedupedCommits,
      cwd: options.cwd ?? process.cwd(),
      dependencies: resolvePackageDependencies(plan, "."),
      highlights: options.highlights,
      headerLabel: options.headerLabel,
    },
    {
      includeFooter: options.includeFooter,
    },
  );
}

/**
 * Locate a manual-notes block at the top of an existing changelog and split it
 * out. The notes block is the first release-level heading whose text is not a
 * version (`##` for markdown, `#` for r-news), captured up to — but excluding —
 * the first subsequent version heading at the same level.
 *
 * Returns the captured prose as `highlights` (the heading line itself dropped,
 * trimmed) and the changelog with that block removed as `body`. When the first
 * release-level heading is already a version, or there is none, nothing is
 * stripped and `highlights` is empty.
 *
 * Only the topmost heading is ever eligible, and capture stops at the first
 * version heading, so prior releases are never swallowed. For r-news this also
 * subsumes the conventional `# pkg (development version)` header, whose body
 * (if any) becomes the release notes.
 */
export function extractUnreleasedNotes(
  existing: string,
  format: VersionaryChangelogFormat = "markdown-changelog",
): { highlights: string; body: string } {
  const headingPattern = format === "r-news" ? /^#(?!#)\s+/u : /^##(?!#)\s+/u;
  const lines = existing.split("\n");

  let firstHeadingIdx = -1;
  for (let index = 0; index < lines.length; index += 1) {
    if (headingPattern.test(lines[index])) {
      firstHeadingIdx = index;
      break;
    }
  }

  if (firstHeadingIdx === -1 || isVersionHeading(lines[firstHeadingIdx])) {
    return { highlights: "", body: existing };
  }

  let nextVersionIdx = lines.length;
  for (let index = firstHeadingIdx + 1; index < lines.length; index += 1) {
    if (headingPattern.test(lines[index]) && isVersionHeading(lines[index])) {
      nextVersionIdx = index;
      break;
    }
  }

  const highlights = lines
    .slice(firstHeadingIdx + 1, nextVersionIdx)
    .join("\n")
    .trim();
  const body = [
    ...lines.slice(0, firstHeadingIdx),
    ...lines.slice(nextVersionIdx),
  ].join("\n");
  return { highlights, body };
}

export function prependChangelog(
  cwd: string,
  changelogFile: string,
  section: string,
  format: VersionaryChangelogFormat = "markdown-changelog",
): void {
  const changelogPath = path.join(cwd, changelogFile);
  const existingRaw = fs.existsSync(changelogPath)
    ? fs.readFileSync(changelogPath, "utf8")
    : "";
  // Strip any manual-notes block; its prose is folded into `section` upstream,
  // so leaving it here would duplicate it.
  const { body: existing } = extractUnreleasedNotes(existingRaw, format);
  if (format === "r-news") {
    const separator = existing.length > 0 ? "\n\n" : "";
    const next = `${`${section}${separator}${existing}`.trimEnd()}\n`;
    fs.writeFileSync(changelogPath, next, "utf8");
    return;
  }
  const heading = "# Changelog\n\n";
  const bodyWithoutHeading = existing.replace(/^# Changelog\s*/u, "");
  const separator = bodyWithoutHeading.length > 0 ? "\n\n" : "";
  const next = `${`${heading}${section}${separator}${bodyWithoutHeading}`.trimEnd()}\n`;
  fs.writeFileSync(changelogPath, next, "utf8");
}

export function renderRNewsReleaseNotes(input: {
  packageName: string;
  nextVersion: string;
  commits: ParsedCommit[];
  cwd?: string;
  highlights?: string;
}): string {
  const repoUrl = resolveRepositoryWebBaseUrl(input.cwd ?? process.cwd());
  const grouped = groupCommitLines(input.commits, repoUrl);
  const normalizedVersion = input.nextVersion.replace(/\.\d+$/u, "");
  const sections: string[] = [];
  const trimmedHighlights = input.highlights?.trim() ?? "";
  if (trimmedHighlights.length > 0) {
    sections.push(trimmedHighlights, "");
  }
  if (grouped.breaking.length > 0) {
    sections.push("## Breaking changes", "", ...grouped.breaking, "");
  }
  if (grouped.features.length > 0) {
    sections.push("## Features", "", ...grouped.features, "");
  }
  if (grouped.fixes.length > 0) {
    sections.push("## Bug fixes", "", ...grouped.fixes, "");
  }
  if (grouped.performance.length > 0) {
    sections.push(
      "## Performance improvements",
      "",
      ...grouped.performance,
      "",
    );
  }
  if (grouped.reverts.length > 0) {
    sections.push("## Reverts", "", ...grouped.reverts, "");
  }
  if (needsOtherChangesFallback(grouped, trimmedHighlights.length > 0, 0)) {
    sections.push("## Other changes", "", ...grouped.other, "");
  }
  return [`# ${input.packageName} ${normalizedVersion}`, "", ...sections]
    .join("\n")
    .trimEnd();
}
